url: "http://airborn12.github.io/demo"
pygments: true
permalink: /demo/blog/:year/:month/:title/
markdown: rdiscount

exclude: ["Rakefile", "README.markdown"]

paginate: 10
pagination_roots: ["/demo/blog"]

sitename: "David Lynch"
subtitle: "is not a director"

author: "David Lynch"
email: "kemayo@gmail.com"

tag_dir: "blog/tag"
